// Code generated by goctl. DO NOT EDIT!
// Source: search.proto

package server

import (
	"context"

	"mall/service/search/rpc/internal/logic"
	"mall/service/search/rpc/internal/svc"
	"mall/service/search/rpc/search"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	search.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) Search(ctx context.Context, in *search.SearchRequest) (*search.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}

func (s *SearchServer) Pinyin(ctx context.Context, in *search.PinyinRequest) (*search.PinyinResponse, error) {
	l := logic.NewPinyinLogic(ctx, s.svcCtx)
	return l.Pinyin(in)
}

func (s *SearchServer) Banned(ctx context.Context, in *search.BannedRequest) (*search.BannedResponse, error) {
	l := logic.NewBannedLogic(ctx, s.svcCtx)
	return l.Banned(in)
}
