// Code generated by goctl. DO NOT EDIT!
// Source: vip.proto

package server

import (
	"context"

	"mall/service/vip/rpc/internal/logic"
	"mall/service/vip/rpc/internal/svc"
	"mall/service/vip/rpc/vip"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	vip.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) Create(ctx context.Context, in *vip.CreateRequest) (*vip.CreateResponse, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *ProductServer) Update(ctx context.Context, in *vip.UpdateRequest) (*vip.UpdateResponse, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *ProductServer) Remove(ctx context.Context, in *vip.RemoveRequest) (*vip.RemoveResponse, error) {
	l := logic.NewRemoveLogic(ctx, s.svcCtx)
	return l.Remove(in)
}

func (s *ProductServer) Detail(ctx context.Context, in *vip.DetailRequest) (*vip.DetailResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
